version: "3.9"

services:
  server:
    build:
      context: .
      dockerfile: docker/Dockerfile.server
    volumes:
      - .:/app
    command: air
    environment:
      CUSTOS_ENV: development
    ports:
      - "8080:8080"
